package com.example.animalclassifierv3;

public class AnimalClasses {
  public static String[] ANIMAL_CLASSES = new String[]{
      "Tence fish",
      "Goldfish",
      "Great white shark",
      "tiger shark",
      "Hammerhead shark",
      "Electric ray / Crampfish",
      "stingray",
      "cock",
      "hen",
      "Ostrich",
      "Brambling bird",
      "goldfinch",
      "House finch / linnet",
      "Junco / snowbird",
      "Indigo bunting",
      "American Robin",
      "bulbul",
      "Jay",
      "Magpie",
      "Chickadee",
      "Water ouzel, dipper",
      "Kite",
      "Eagle",
      "Vulture",
      "Owl",
      "European fire salamander",
      "Common newt",
      "Eft",
      "Spotted salamander",
      "Axolotl",
      "Bullfrog",
      "Tree frog",
      "Tailed frog",
      "Loggerhead turtle",
      "Leatherback turtle",
      "Mud turtle",
      "Terrapin",
      "Box turtle",
      "Banded gecko",
      "Iguana",
      "American Chameleon",
      "Whiptail Lizard",
      "Agama",
      "Frilled Lizard",
      "Alligator lizard",
      "Gila monster",
      "Green Lizard",
      "African Chameleon",
      "Komodo dragon",
      "African Crocodile",
      "American Alligator",
      "Triceratops",
      "Thunder snake / Worm snake",
      "Ringneck snake",
      "Sand viper",
      "Green snake / Grass snake",
      "King snake",
      "Garter snake / Grass snake",
      "Water snake",
      "Vine snake",
      "Night snake",
      "Boa constrictor",
      "Rock python",
      "Indian cobra",
      "Green mamba",
      "Sea snake",
      "Horned viper",
      "Diamondback rattlesnake",
      "Sidewinder / Horned rattlesnake",
      "Trilobite",
      "Harvestman spider",
      "Scorpion",
      "Black and gold garden spider",
      "Barn spider",
      "Garden spider",
      "Black widow",
      "Tarantula",
      "Wolf spider",
      "Tick",
      "Centipede",
      "Black grouse",
      "Ptarmigan",
      "Ruffed grouse / Partridge",
      "Prairie fowl",
      "Peacock",
      "Quail",
      "Partridge",
      "African grey",
      "Macaw",
      "Sulphur-crested cockatoo",
      "Lorikeet",
      "Coucal",
      "Bee eater",
      "Hornbill",
      "Hummingbird",
      "Jacamar",
      "Toucan",
      "Drake",
      "Red-breasted merganser",
      "Goose",
      "Black swan",
      "Tusker",
      "Echidna / Ant eater",
      "Platypus",
      "Brush kangaroo",
      "Koala bear",
      "Wombat",
      "Jellyfish",
      "Sea anemone, anemone",
      "Brain coral",
      "Flatworm",
      "Nematode worm / roundworm",
      "Conch",
      "Snail",
      "Slug",
      "Sea slug",
      "Chiton / sea cradle",
      "Chambered nautilus",
      "Dungeness crab",
      "Rock crab",
      "Fiddler crab",
      "King crab",
      "American lobster",
      "Spiny lobster / Crayfish",
      "Crayfish / Crawfish",
      "Hermit crab",
      "Isopod",
      "White stork",
      "Black stork",
      "Spoonbill",
      "Flamingo",
      "Little blue heron",
      "Great white heron",
      "Bittern",
      "Crane",
      "Limpkin",
      "European Gallinule",
      "American coot",
      "Bustard",
      "Ruddy Turnstone",
      "Red-backed sandpiper",
      "Redshank",
      "Dowitcher",
      "Oyster catcher",
      "Pelican",
      "King Penguin",
      "Albatross",
      "Grey whale",
      "Killer whale / Orca",
      "Dugong",
      "Sea lion",
      "Chihuahua",
      "Japanese spaniel",
      "Maltese terrier",
      "Pekinese",
      "Shih-Tzu",
      "Blenheim spaniel",
      "Papillon",
      "Toy terrier",
      "Rhodesian ridgeback",
      "Afghan hound, Afghan",
      "Basset hound",
      "Beagle Dog",
      "Bloodhound",
      "Bluetick",
      "Black-and-tan coonhound",
      "Walker hound",
      "English foxhound",
      "Redbone",
      "Russian wolfhound",
      "Irish wolfhound",
      "Italian greyhound",
      "Whippet",
      "Ibizan hound",
      "Norwegian elkhound",
      "Otter hound",
      "Gazelle hound",
      "Scottish deerhound",
      "Weimaraner",
      "Staffordshire bull terrier",
      "American pit bull terrier",
      "Bedlington terrier",
      "Border terrier",
      "Kerry blue terrier",
      "Irish terrier",
      "Norfolk terrier",
      "Norwich terrier",
      "Yorkshire terrier",
      "Wire-haired fox terrier",
      "Lakeland terrier",
      "Sealyham terrier",
      "Airedale terrier",
      "Cairn terrier",
      "Australian terrier",
      "Dandie Dinmont terrier",
      "Boston bull / Boston terrier",
      "Miniature schnauzer",
      "Giant schnauzer",
      "Standard schnauzer",
      "Scottish terrier",
      "Tibetan terrier",
      "Silky terrier",
      "Soft-coated wheaten terrier",
      "West Highland white terrier",
      "Lhasa / Lhasa apso",
      "Flat-coated retriever",
      "Curly-coated retriever",
      "Golden retriever",
      "Labrador retriever",
      "Chesapeake Bay retriever",
      "German short-haired pointer",
      "Vizsla, Hungarian pointer",
      "English setter",
      "Irish setter, red setter",
      "Gordon setter",
      "Brittany spaniel",
      "Clumber, clumber spaniel",
      "English springer spaniel",
      "Welsh springer spaniel",
      "Cocker spaniel",
      "Sussex spaniel",
      "Irish water spaniel",
      "Kuvasz",
      "Schipperke",
      "Groenendael",
      "Malinois",
      "Briard",
      "Kelpie",
      "Komondor",
      "Old English sheepdog",
      "Shetland sheepdog",
      "Collie",
      "Border collie",
      "Bouvier des Flandres",
      "Rottweiler",
      "German shepherd",
      "Doberman pinscher",
      "Miniature pinscher",
      "Greater Swiss Mountain dog",
      "Bernese mountain dog",
      "Appenzeller",
      "EntleBucher",
      "Boxer",
      "Bull mastiff",
      "Tibetan mastiff",
      "French bulldog",
      "Great Dane",
      "Saint Bernard, St Bernard",
      "Eskimo dog, husky",
      "Malamute  / Alaskan malamute",
      "Siberian husky",
      "Dalmatian",
      "Monkey pinscher",
      "Basenji",
      "Pug-dog",
      "Leonberg",
      "Newfoundland dog",
      "Great Pyrenees",
      "Samoyed",
      "Pomeranian",
      "Chow chow",
      "Keeshond",
      "Brabancon griffon",
      "Pembroke Welsh corgi",
      "Cardigan Welsh corgi",
      "Toy poodle",
      "Miniature poodle",
      "Standard poodle",
      "Mexican hairless",
      "Gray wolf",
      "White wolf",
      "Red wolf",
      "Coyote / Prairie wolf / Brush wolf",
      "Dingo",
      "Dhole",
      "African hunting dog / Hyena dog",
      "Hyaena",
      "Red fox",
      "Kit fox",
      "Arctic fox",
      "Gray fox",
      "Tabby cat",
      "Tiger cat",
      "Persian cat",
      "Siamese cat",
      "Egyptian cat",
      "Cougar / Puma / Panther",
      "Lynx",
      "Leopard",
      "Snow leopard",
      "Jaguar / Panther",
      "Lion",
      "Tiger",
      "Cheetah",
      "Brown bear",
      "Black bear",
      "Polar bear",
      "Sloth bear",
      "Mongoose",
      "Meerkat",
      "Tiger beetle",
      "Ladybug",
      "Ground beetle",
      "Long-horned beetle",
      "Leaf beetle",
      "Dung beetle",
      "Rhinoceros beetle",
      "Weevil",
      "Fly",
      "Bee",
      "Ant",
      "Grasshopper",
      "Cricket",
      "Walking stick insect",
      "Cockroach",
      "Mantis",
      "Cicada",
      "Leafhopper",
      "Lacewing fly",
      "Dragonfly",
      "Damselfly",
      "Admiral",
      "Ringlet butterfly",
      "Monarch butterfly",
      "Cabbage butterfly",
      "Sulphur butterfly",
      "Lycaenid butterfly",
      "Starfish",
      "Sea urchin",
      "Sea cucumber",
      "Wood rabbit / Cottontail rabbit",
      "Hare",
      "Angora",
      "Hamster",
      "Porcupine / Hedgehog",
      "Fox squirrel",
      "Marmot",
      "Beaver",
      "Guinea pig",
      "Horse",
      "Zebra",
      "Pig",
      "Wild boar",
      "Warthog",
      "Hippopotamus",
      "Ox",
      "Water buffalo",
      "Bison",
      "Ram, Tup",
      "Rocky Mountain bighorn sheep",
      "Ibex",
      "Hartebeest",
      "Impala",
      "Gazelle",
      "Camel",
      "Llama",
      "Weasel",
      "Mink",
      "Polecat",
      "Black-footed ferret",
      "Otter",
      "Skunk / Polecat",
      "Badger",
      "Armadillo",
      "Three-toed sloth",
      "Orangutan",
      "Gorilla",
      "Chimpanzee",
      "Gibbon",
      "Siamang",
      "Guenon monkey",
      "Hussar monkey",
      "Baboon",
      "Macaque",
      "Langur",
      "Colobus monkey",
      "Proboscis monkey",
      "Marmoset",
      "Capuchin",
      "Howler monkey",
      "Titi monkey",
      "Spider monkey",
      "Squirrel monkey",
      "Madagascar cat",
      "Indri",
      "Indian elephant",
      "African elephant",
      "Red panda / Beer cat",
      "Panda",
      "Barracouta",
      "Eel",
      "Silver salmon",
      "Rock beauty",
      "Anemone fish",
      "Sturgeon",
      "Garfish",
      "Lionfish",
      "Puffer fish"
  };

  public static String[] ANIMAL_CLASSES_BANGLA = new String[] {
          "টেঞ্চফিশ (মাছ)",
          "গোল্ডফিশ (মাছ)",
          "সাদা হাঙর",
          "টাইগার হাঙর",
          "হ্যামারহেড হাঙর",
          "বৈদ্যুতিক রে, ক্র্যাম্পফিশ (মাছ)",
          "শাপলাপাতা মাছ",
          "মোরগ",
          "মুরগি",
          "উটপাখি",
          "ব্র্যাম্বলিং পাখি",
          "গোল্ডেন ফিঞ্চ (পাখি)",
          "হাউজ ফিঞ্চ (পাখি)",
          "স্নো বার্ড (পাখি)",
          "ইন্ডিগো বার্ড (পাখি)",
          "আমেরিকান রবিন পাখি",
          "বুলবুল পাখি",
          "নীলকণ্ঠী পাখি",
          "দোয়েল পাখি",
          "চিকাডি পাখি",
          "ওয়াটার অউজেল, ডিপার পাখি",
          "কাইট পাখি",
          "ঈগল পাখি",
          "শকুন",
          "ধূসর পেঁচা",
          "ফায়ার স্যালাম্যান্ডার (গিরগিটিসদৃশ প্রাণী)",
          "গুইসাপ",
          "এফট (গুইসাপ জাতীয়)",
          "স্পটেড স্যালাম্যান্ডার (গিরগিটিসদৃশ প্রাণী)",
          "একজোলটল (গিরগিটিসদৃশ প্রাণী)",
          "কোলাব্যাঙ",
          "গেছোব্যাঙ",
          "টেইল্ড ফ্রগ (ব্যাঙ)",
          "লগারহেড কচ্ছপ",
          "লেদারব্যাক কচ্ছপ",
          "মাড টার্টল (মাটির কচ্ছপ)",
          "টেরাপিন টার্টল (নদীচর কচ্ছপ)",
          "বক্স কচ্ছপ",
          "ব্যান্ডেড গেকো (গিরগিটিসদৃশ প্রাণী)",
          "ইগুয়ানা",
          "ক্যামেলিওন (বহুরূপী গিরগিটি)",
          "হুইপটেইল গিরগিটি",
          "আগামা (টিকটিকি সদৃশ)",
          "ফ্রিল্ড গিরগিটি",
          "আলিগেটর গিরগিটি",
          "গিলা মন্সটার (গিরগিটিসদৃশ প্রাণী)",
          "সবুজ লিজার্ড (গিরগিটিসদৃশ প্রাণী)",
          "আফ্রিকান ক্যামেলিওন (গিরগিটি)",
          "কমোডো ড্রাগন",
          "আফ্রিকান কুমির",
          "আমেরিকান কুমির",
          "ট্রাইসেরাটপ্স",
          "বজ্র সাপ",
          "রিং নেক সাপ",
          "স্যান্ড ভাইপার সাপ",
          "সবুজ সাপ",
          "কিং সাপ",
          "গার্টার সাপ",
          "পানি সাপ",
          "পাতি লাউডগা সাপ",
          "নাইট সাপ",
          "পার্বত সাপ",
          "রক পাইথন সাপ",
          "কোবরা সাপ",
          "গ্রিন মাম্বা সাপ",
          "সি স্নেক",
          "স্যান্ড ভাইপার সাপ",
          "ডায়মন্ডব্যাক র‍্যাটলস্নেক (ঠকঠকি সাপ)",
          "সাইডউইন্ডার র‍্যাটল স্নেক (ঠকঠকি সাপ)",
          "ট্রাইলো বাইট",
          "হার্ভেস্ট ম্যান মাকড়সা",
          "বিছা",
          "কালো-সোনালী বাগান মাকড়সা",
          "বার্ন স্পাইডার (মাকড়সা)",
          "গার্ডেন স্পাইডার (মাকড়সা)",
          "ব্ল্যাক উইডো মাকড়সা",
          "টারান্টুলা মাকড়সা",
          "ওলফ স্পাইডার (মাকড়সা)",
          "টিক (পোকা বিশেষ)",
          "শতপদী / কেন্নো",
          "ব্ল্যাক গ্রাউস পাখি (বুনো মুরগি জাতীয়)",
          "টার্মিগান পাখি (বুনো মুরগি জাতীয়)",
          "রাফড গ্রাউস পাখি (বুনো মুরগি জাতীয়)",
          "প্রেইরি চিকেন (বুনো মুরগি জাতীয়)",
          "ময়ূর",
          "কুয়েইল পাখি (তিতির জাতীয় ছোট পাখি)",
          "পারট্রিজ পাখি (তিতির জাতীয় পাখি)",
          "আফ্রিকান টিয়া পাখি",
          "তোতাপাখি",
          "সালফার ক্রেস্টেড কাকাতুয়া",
          "লরিকিট পাখি (টিয়া সদৃশ)",
          "বড় কুবো পাখি",
          "সবুজ বাঁশপাতি পাখি",
          "ধনেশ পাখি",
          "হামিং বার্ড",
          "পতঙ্গখেকো জাকামার পাখি",
          "দীর্ঘচঞ্চু পাখি",
          "পাতিহাঁস",
          "লাল-বুক মার্গানসার (পাতিহাঁস বিশেষ)",
          "রাজহাঁস",
          "ব্ল্যাক সোয়ান (কালো রাজহাঁস)",
          "টাস্কার",
          "পিঁপড়া খেকো একিডনা",
          "প্লাটীপাস",
          "ক্যাঙ্গারু",
          "কোয়ালা",
          "ওমব্যাট (ছোট ভালুক জাতীয়)",
          "জেলিফিশ",
          "সি এনিমোন (সামুদ্রিক প্রাণীবিশেষ)",
          "ব্রেইন কোরাল (প্রবাল বিশেষ)",
          "চ্যাপ্টা কৃমি",
          "সুতা কৃমি",
          "শাঁখ",
          "শামুক",
          "স্লাগ (খোলসবিহীন শামুকসদৃশ)",
          "সামুদ্রিক স্লাগ (খোলসবিহীন শামুকসদৃশ)",
          "চিটন",
          "নটিলাস (সামুদ্রিক শামুক সদৃশ)",
          "দাঞ্জনেস কাঁকড়া",
          "পাথুরে কাঁকড়া",
          "ফিডলার কাঁকড়া",
          "আলস্কা কিং ক্র্যাব (কাঁকড়া)",
          "আমেরিকান লবস্টার (কাঁকড়া)",
          "স্পাইনি লবস্টার",
          "ক্রেফিশ",
          "হারমিট ক্র্যাব (কাঁকড়া)",
          "আইসোপড",
          "সাদা সারস পাখি",
          "কালো সারস",
          "স্পুনবিল (সারস সদৃশ)",
          "কলহংস",
          "হেরন পাখি(বক)",
          "সাদা বক পাখি",
          "বিটার্ন পাখি",
          "সারস পাখি",
          "লিম্পকিন পাখি",
          "ইউরোপীয় গ্যালিনুল (জলমুরগি)",
          "আমেরিকান কুট পাখি",
          "বাস্টার্ড পাখি",
          "রুডী টার্ন্সটোন পাখি",
          "চা পাখি",
          "লালপা পি-উ",
          "ডু উইচার পাখি",
          "অয়েস্টার ক্যাচার পাখি",
          "গগণবেড় পাখি",
          "কিং পেঙ্গুইন",
          "এলবাট্রস পাখি",
          "ধূসর তিমি",
          "শিকারী তিমি / অরকা",
          "সমুদ্র ধেনু",
          "সীলমাছ",
          "চিহুয়াহুয়া কুকুর",
          "জাপানিজ স্প্যানিয়েল কুকুর",
          "ম্যাল্টেজ টেরিয়ার কুকুর",
          "পেকিনিজ কুকুর",
          "শি-জু কুকুর",
          "ব্লেনহিম স্প্যানিয়েল কুকুর",
          "প্যাপিলন কুকুর",
          "টয় টেরিয়ার কুকুর",
          "রোডেশিয়ান রিজব্যাক কুকুর",
          "আফঘান হাউন্ড কুকুর",
          "বাসেট হাউন্ড কুকুর",
          "বিগল কুকুর",
          "ব্লাডহাউন্ড কুকুর",
          "ব্লুটিক কুকুর",
          "কুন হাউন্ড কুকুর",
          "ওয়াকার হাউন্ড কুকুর",
          "ইংলিশ ফক্সহাউন্ড কুকুর",
          "রেডবোন কুকুর",
          "রাশিয়ান ওলফহাউন্ড কুকুর",
          "আইরিশ ওলফহাউন্ড কুকুর",
          "ইটালিয়ান গ্রে হাউন্ড কুকুর",
          "হুইপেট কুকুর",
          "ইবিজান হাউন্ড কুকুর",
          "নরওয়েজিয়ান এল্ক হাউন্ড কুকুর",
          "ওটার হাউন্ড কুকুর",
          "গ্যাজেল হাউন্ড কুকুর",
          "স্কটিশ ডিয়ারহাউন্ড কুকুর",
          "ওয়েইমারেনার কুকুর",
          "বুল টেরিয়ার কুকুর",
          "আমেরিকান পিট বুল টেরিয়ার কুকুর",
          "বেডলিংটন টেরিয়ার কুকুর",
          "বর্ডার টেরিয়ার কুকুর",
          "কেরি ব্লু টেরিয়ার কুকুর",
          "আইরিশ টেরিয়ার কুকুর",
          "নরফোক টেরিয়ার কুকুর",
          "নরঊইচ টেরিয়ার কুকুর",
          "ইয়র্কশায়ার টেরিয়ার কুকুর",
          "অয়্যার হেয়ারড ফক্স টেরিয়ার কুকুর",
          "লেকল্যান্ড টেরিয়ার কুকুর",
          "সিলাইহাম টেরিয়ার কুকুর",
          "এয়ারডেল টেরিয়ার কুকুর",
          "কাইর্ন টেরিয়ার কুকুর",
          "অস্ট্রেলিয়ান টেরিয়ার কুকুর",
          "ডান্ডি ডিনমোন্ট টেরিয়ার কুকুর",
          "বস্টন টেরিয়ার কুকুর",
          "মিনিয়েচার স্নাউজার কুকুর",
          "জায়ান্ট স্নাউজার কুকুর",
          "সাধারণ স্নাউজার কুকুর",
          "স্কচ টেরিয়ার কুকুর",
          "তিবেতিয়ান টেরিয়ার কুকুর",
          "সিল্কি টেরিয়ার কুকুর",
          "সফট কোটেড হুইটেন টেরিয়ার কুকুর",
          "ওয়েস্ট হাইল্যান্ড হোয়াইট টেরিয়ার কুকুর",
          "লাসা আপসো কুকুর",
          "ফ্ল্যাট কোটেড রিট্রিভার কুকুর",
          "কারলি কোটেড রিট্রিভার কুকুর",
          "গোল্ডেন রিট্রিভার কুকুর",
          "ল্যাবরেডর রিট্রিভার কুকুর",
          "চিসাপিক বে রিট্রিভার কুকুর",
          "জার্মান শর্ট হেয়ার্ড পয়েন্টার কুকুর",
          "হাঙ্গেরিয়ান পয়েন্টার কুকুর",
          "ইংলিশ সেটার কুকুর",
          "আইরিশ সেটার কুকুর",
          "গর্ডন সেটার কুকুর",
          "ব্রিটানি স্প্যানিয়েল কুকুর",
          "ক্লাম্বার স্প্যানিয়েল কুকুর",
          "ইংলিশ স্প্রিঙ্গার স্প্যানিয়েল কুকুর",
          "ওয়েলশ স্প্রিঙ্গার স্প্যানিয়েল কুকুর",
          "ককার স্প্যানিয়েল কুকুর",
          "সাসেক্স স্প্যানিয়েল কুকুর",
          "আইরিশ ওয়াটার স্প্যানিয়েল কুকুর",
          "কুভাজ কুকুর",
          "শিপার্ক কুকুর",
          "গ্রেনেনডেল কুকুর",
          "ম্যালিনইজ কুকুর",
          "ব্রাইয়ার্ড কুকুর",
          "কেল্পি কুকুর",
          "কমনডোর কুকুর",
          "ববটেইল কুকুর",
          "শেটল্যান্ড শিপডগ কুকুর",
          "কলি কুকুর",
          "বর্ডার কলি কুকুর",
          "ফ্ল্যান্ড্রেস কুকুর",
          "রটওয়েইলার কুকুর",
          "জার্মান শেপহার্ড কুকুর",
          "ডোবারম্যান কুকুর",
          "মিনিয়েচার পিনশার কুকুর",
          "সুইস পাহাড়ি কুকুর কুকুর",
          "বার্নিজ পাহাড়ি কুকুর কুকুর",
          "এপেনজেলার কুকুর",
          "এনটেলবুচার কুকুর",
          "বক্সার কুকুর",
          "বুল মাস্তিফ কুকুর",
          "তিবেতিয়ান মাস্তিফ কুকুর",
          "ফ্রেঞ্চ বুলডগ কুকুর",
          "গ্রেট ডেইন কুকুর",
          "সেইন্ট বার্নার্ড কুকুর",
          "হাস্কি কুকুর",
          "আলাস্কান মালামুট কুকুর",
          "সাইবেরিয়ান হাস্কি কুকুর",
          "ডাল্মাটিয়ান কুকুর",
          "মাংকি পিনশার কুকুর",
          "বাসেঞ্জি কুকুর",
          "পাগ ডগ কুকুর",
          "লেওনবার্গ কুকুর",
          "নিউ ফাউন্ডল্যান্ড ডগ কুকুর",
          "গ্রেট পাইরেনিজ কুকুর",
          "সামোয়েড কুকুর",
          "পমেরানিয়ান কুকুর",
          "চাও চাও কুকুর",
          "কিশান্ড কুকুর",
          "ব্রাবানকোন গ্রিফন কুকুর",
          "পেমব্রোক করগি কুকুর",
          "কার্ডিগান করগি কুকুর",
          "টয় পুডল কুকুর",
          "মিনিয়েচার পুডল কুকুর",
          "সাধারণ পুডল কুকুর",
          "মেক্সিকান হেয়ারলেস কুকুর",
          "ধূসর নেকড়ে",
          "সাদা নেকড়ে",
          "লাল নেকড়ে",
          "কোয়োট নেকড়ে",
          "ডিনগো নেকড়ে",
          "ঢোল (নেকড়ে বিশেষ)",
          "আফ্রিকান শিকারী কুকুর",
          "হায়েনা",
          "লাল শেয়াল",
          "খেঁক শেয়াল",
          "সাদা আর্কটিক শেয়াল",
          "ধূসর শেয়াল",
          "ট্যাবি ক্যাট (বিড়াল এর জাত)",
          "টাইগার ক্যাট (বিড়াল এর জাত)",
          "পার্সিয়ান বিড়াল",
          "সিয়ামেজ বিড়াল",
          "মিসরীয় বিড়াল",
          "চিতাবাঘ / প্যান্থার",
          "লিংক্স (বনবিড়াল বিশেষ)",
          "লেপার্ড (চিতাবাঘ সদৃশ)",
          "স্নো লেপার্ড (চিতাবাঘ সদৃশ)",
          "জাগুয়ার বাঘ",
          "সিংহ",
          "বাঘ",
          "চিতা",
          "বাদামী ভালুক",
          "কালো ভালুক",
          "মেরু ভালুক",
          "স্লথ ভালুক",
          "বেজি",
          "মিরক্যাট (ছোট আকারের বেজি)",
          "বাঘ পোকা (গুবরে পোকা বিশেষ)",
          "গুবরে পোকা",
          "গ্রাউন্ড বিটল (গুবরে পোকা বিশেষ)",
          "লং হোর্ন্ড বিটল (গুবরে পোকা বিশেষ)",
          "লিফ বিটল (গুবরে পোকা বিশেষ)",
          "ডাং বিটল (গুবরে পোকা বিশেষ)",
          "রাইনো বিটল (গুবরে পোকা বিশেষ)",
          "শুঁড়পোকা",
          "মাছি",
          "মৌমাছি",
          "পিঁপড়া",
          "ঘাসফড়িং",
          "ঝিঁঝিঁ পোকা",
          "পাতা সদৃশ পোকা",
          "আরশোলা",
          "ম্যান্টিস",
          "সিকাডা (পোকাবিশেষ)",
          "লিফ হপার",
          "লেসউইং ফ্লাই (পোকাবিশেষ)",
          "ড্রাগন ফ্লাই",
          "ড্যামজেল ফ্লাই",
          "এডমিরাল প্রজাপতি",
          "রিংলেট প্রজাপতি",
          "মনার্ক প্রজাপতি",
          "ক্যাবেজ প্রজাপতি",
          "সালফার প্রজাপতি",
          "লিসেনিড প্রজাপতি",
          "স্টারফিশ",
          "সি আর্চিন",
          "সি কিউকাম্বার",
          "কটনটেইল খরগোশ",
          "খরগোশ",
          "এংগোরা খরগোশ",
          "হ্যামস্টার",
          "সজারু",
          "কাঠবিড়ালী",
          "মারমোট (কাঠবিড়ালী সদৃশ)",
          "বিভার",
          "গিনি পিগ",
          "ঘোড়া",
          "জেব্রা",
          "শূকর",
          "বুনো শুকর (বোয়ার)",
          "বুনো শুকর (ওয়ার্থগ)",
          "জলহস্তী",
          "মহিষ",
          "ওয়াটার অক্স (মহিষ)",
          "বাইসন",
          "ভেড়া",
          "পাহাড়ি ভেড়া",
          "আইবেক্স (বন্য ছাগল)",
          "হার্টবিস্ট (হরিণ সদৃশ)",
          "ইমপালা",
          "গজলা হরিণ",
          "আরব উট",
          "লামা",
          "নেউল / বেজি",
          "মিঙ্ক (ছোট বেজি জাতীয়)",
          "পোল ক্যাট (বেজি জাতীয়)",
          "ফেরেট (বেজি জাতীয়)",
          "ভোঁদড়",
          "স্কাঙ্ক (বেজি জাতীয়)",
          "ব্যাজার (এক প্রকার নিশাচর প্রাণী)",
          "আর্মাডিলো",
          "স্লথ",
          "ওরাংওটান",
          "গরিলা",
          "শিম্পাঞ্জি",
          "গিবন (বানর সদৃশ)",
          "সিয়ামাং (বানর সদৃশ)",
          "গেনন বানর",
          "হুসার বানর",
          "বেবুন",
          "ম্যাকাক বানর",
          "লাঙ্গুর বানর",
          "কলোবাস বানর",
          "প্রবোসকিস বানর",
          "মার্মোসেট বানর",
          "ক্যাপুচিন বানর",
          "হাওলার বানর",
          "তিতি বানর",
          "স্পাইডার বানর",
          "স্কুইরেল বানর",
          "মাদাগাস্কার বিড়াল",
          "ইন্দ্রি (বানর বিশেষ)",
          "ভারতীয় হাতি",
          "আফ্রিকান হাতি",
          "লাল পান্ডা",
          "পান্ডা",
          "ব্যারাকুটা মাছ",
          "ঈল",
          "স্যালমন মাছ",
          "রক বিউটি এঞ্জেল ফিশ (মাছ)",
          "এনেমোন ফিশ (মাছ)",
          "স্টার্জন মাছ",
          "গারফিস (মাছ)",
          "লায়ন ফিশ (মাছ)",
          "পটকা মাছ"
  };
}
